#ifndef ALEXNET_BUFFER_LAYOUT_H
#define ALEXNET_BUFFER_LAYOUT_H

#define ALEXNET_BASE_ALIGNMENT          128u
#define ALEXNET_DMA_ALIGNMENT             8u

#define ALEXNET_CAMERA_WIDTH             224u
#define ALEXNET_CAMERA_HEIGHT            224u
#define ALEXNET_CAMERA_PIXEL_STRIDE         8u
#define ALEXNET_BATCH_SIZE                  8u
#define ALEXNET_CAMERA_IMAGE_BYTES      401408u
#define ALEXNET_CAMERA_BUFFER_BYTES    3211264u
#define ALEXNET_CAMERA_N8_LANE_MASK       0x07u

#define ALEXNET_CONV1_RAW_BYTES          193600u
#define ALEXNET_CONV2_RAW_BYTES          139968u
/* Raw-result capacity rounded up to the 128-byte base-address ABI. */
#define ALEXNET_ACTIVATION_IMAGE_STRIDE  262144u
#define ALEXNET_BATCH_ACTIVATION_OFFSET 2097152u
#define ALEXNET_ACTIVATION_A_BYTES      2129920u
#define ALEXNET_ACTIVATION_B_BYTES      2129920u
#define ALEXNET_WEIGHT_BYTES          61123264u
#define ALEXNET_PARAMETER_BYTES         165504u
#define ALEXNET_OUTPUT_IMAGE_BYTES         1000u
#define ALEXNET_OUTPUT_VALID_BYTES         8000u
#define ALEXNET_OUTPUT_ALLOC_BYTES         8064u

/* One coherent DDR allocation; every programmed base is 128-byte aligned. */
#define ALEXNET_BUFFER_INPUT_OFFSET           0u
#define ALEXNET_BUFFER_ACT_A_OFFSET     3211264u
#define ALEXNET_BUFFER_ACT_B_OFFSET     5341184u
#define ALEXNET_BUFFER_WEIGHTS_OFFSET   7471104u
#define ALEXNET_BUFFER_PARAMETERS_OFFSET 68594432u
#define ALEXNET_BUFFER_OUTPUT_OFFSET    68759936u
#define ALEXNET_DMA_USED_BYTES          68768000u

#endif
